

trigger:
  branches:
    include:
    - main

pool: selfhost-aks

stages:

- stage: BuildAndPush
  displayName: 'Build and Push telemtry-query Service'
  jobs:
  - job: dockerbuildandPush
    displayName: 'Build Docker Image and Push to ACR'

    steps:

    - checkout: self
      displayName: 'Checkout Source Code'

    - task: Docker@1
      inputs:
        containerregistrytype: 'Azure Container Registry'
        addBaseImageData: false
        azureSubscriptionEndpoint: 'SVC-AZ-ARM-250926'
        azureContainerRegistry: 'acrashudevka.azurecr.io'
        command: 'login'




