apiVersion: apps/v1
kind: deployment
metadata:
  name: axion-telemetry-query-service
  namespace: axion
  labels:
    app: axion-telemetry-query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-telemetry-query-service
  template:
    metadata:
      labels:
        app: axion-telemetry-query-service
    spec:
      containers:
      - name: axion-telemetry-query-service
        image:  axion-telemetry-query-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
