apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-telemetry-query-service
  namespace: axion
  labels:
    app: axion-telemetry-query-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: axion-telemetry-query-service
  template:
    metadata:
      labels:
        app: axion-telemetry-query-service
    spec:
      containers:
      - name: axion-telemetry-query-service
        image: acrashudevka.azurecr.io/axion-telemetry-query-service:370
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        # env:
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: axion-db-secret
        #       key: DATABASE_URL


